import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "../../components/NavBar";
import MyProfilePic from "../../components/MyProfilePic";
// import HeaderTop from "../../components/HeaderTop";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "sabahat blog",
  description: "Generated by Sabahat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-slate-800`}
      >
        <NavBar/>
        <MyProfilePic/>
        {children}
      </body>
    </html>
  );
}
